#!/usr/bin/env sh

#### AUTOSTART ####
/etc/scripts/bspwm_autostart.sh &

#### BSPWM coloring ####
bspc config active_border_color "#ff79c6"
bspc config focused_border_color "#bd93f9"
bspc config normal_border_color "#44475a"
bspc config presel_feedback_color "#6272a4"
bspc config urgent_border_color "#f85149"

#### BSPWM configuration ####
bspc config external_rules_command /etc/scripts/bspwm_external_rules.sh
bspc config border_width 2
bspc config window_gap "${BSPWM_GAP:-25}"
bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config swallow_first_click false
bspc config focus_follows_pointer true
bspc config bspc config click_to_focus none
bspc config ignore_ewmh_focus true
bspc config single_monocle false

#### BSPWM rules ####
bspc rule -r "*" # clear rules
bspc rule -a sun-awt-X11-XDialogPeer state=floating # java gui fixes
bspc rule -a ".caffeine-wrapped" state=floating
bspc rule -a ".pick-colour-picker-wrapped" state=floating sticky=on
bspc rule -a "Blueberry.py" state=floating
bspc rule -a "Cheese" state=pseudo_tiled
bspc rule -a "Eog" state=floating
bspc rule -a "Evolution-alarm-notify" state=floating sticky=on
bspc rule -a "File-roller" state=floating
bspc rule -a "Geary" state=pseudo_tiled
bspc rule -a "Org.gnome.Nautilus" state=floating sticky=on center=on border=on
bspc rule -a ".thunar-wrapped_" state=floating
bspc rule -a "Gnome-calculator" state=floating
bspc rule -a "Gnome-calendar" state=pseudo_tiled
bspc rule -a "Gnome-font-viewer" state=floating
bspc rule -a "Gnome-sound-recorder" state=pseudo_tiled
bspc rule -a "Gnome-system-monitor" state=floating
bspc rule -a "Image Lounge" state=floating
bspc rule -a "Mysql-workbench-bin" state=pseudo_tiled
bspc rule -a "Nm-connection-editor" state=floating
bspc rule -a "Pavucontrol" state=pseudo_tiled
bspc rule -a "Simplenote" state=tiled
bspc rule -a "Sublime_text" state=floating sticky=on
bspc rule -a "flameshot" state=floating sticky=on
bspc rule -a "kmag" state=floating sticky=on
bspc rule -a "mpv" state=floating
bspc rule -a "Firefox" desktop=^5
bspc rule -a "Google-chrome" desktop=^1
bspc rule -a 'kitty-htop' state=floating sticky=on center=on border=on rectangle=1500x1200+0+0
bspc rule -a 'kitty-scratch' state=floating sticky=on center=on border=on rectangle=1500x1200+0+0
bspc rule -a 'kitty-neorg' state=floating sticky=on center=on border=on rectangle=1500x1200+0+0
bspc rule -a 'kitty-nmtui' state=floating sticky=on center=on border=on rectangle=750x1200+0+0

#### BSPWM workspaces ####
for m in $(xrandr --query | grep " connected" | cut -d" " -f1); do
  bspc monitor "$m" -d 1 2 3 4 F1 F2 F3 F4
done

/etc/scripts/bspwm_subscribe.sh &
/etc/scripts/bspwm_subscribe_polybar.sh &
# /etc/scripts/bspwm_subscribe_exclude_shadow_from_tiled_windows.sh &
# /etc/scripts/bspwm_borders.sh &

sleep 1
firefox > /dev/null 2>&1 &
google-chrome-stable > /dev/null 2>&1 &

bspc config ignore_ewmh_focus false

