#!/usr/bin/env python3
"""Build the final Markdown while escaping non-model metadata."""

import json
import re
import sys
from datetime import datetime, timezone


def markdown_text(value):
    value = re.sub(r"[\r\n]+", " ", str(value)).strip()
    return re.sub(r"([\\`*_{}\[\]()<>#+.!|~-])", r"\\\1", value)


def markdown_url(value):
    return str(value).replace("\\", "%5C").replace("<", "%3C").replace(">", "%3E").replace(" ", "%20")


with open(sys.argv[1], encoding="utf-8") as source:
    article = json.load(source)
output, model, canonical, summary = sys.argv[2:]
title = markdown_text(article.get("title") or "Untitled article")
author = markdown_text(article.get("author") or "")
date = markdown_text(article.get("date") or "")
image = markdown_url(article.get("image_url") or "")
url = markdown_url(canonical)
source_name = markdown_text(re.sub(r"^www\.", "", __import__("urllib.parse").parse.urlsplit(canonical).hostname or "Web article"))
metadata = [f"**Source:** {source_name}"]
if author:
    metadata.append(f"**Author:** {author}")
if date:
    metadata.append(f"**Published:** {date}")
parts = [f"# {title}", "", "::: metadata", " · ".join(metadata), ":::", ""]
if image:
    parts += [f"![Lead image](<{image}>){{.lead-image}}", ""]
parts += [summary.strip(), "", f"[Read the original article](<{url}>){{.original}}", "", "---", "", "::: footer", f"Generated by {markdown_text(model)} at {datetime.now(timezone.utc).isoformat(timespec='seconds')}", ":::", ""]
with open(output, "w", encoding="utf-8") as destination:
    destination.write("\n".join(parts))
