keys:
  - &default age182hl2gfu8zj2dxjdvtfktv9ay57htc20ugjrlmwmv8l806lntdxqgeje73
  - &sandbox age14m8va53kyyzve9vedmq0rn052t8y2esjjr72q8y6gzpegq090ddqacquk5

creation_rules:
  - path_regex: secrets-sops/(local|shared).yaml$
    key_groups:
      - age:
          - *default
          - *sandbox

  - path_regex: secrets-sops/(local|personal|se).yaml$
    key_groups:
      - age:
          - *default
