#!/usr/bin/env sh

#### AUTOSTART ####
wal -R &
alttab -w 1 &
blueberry-tray &
volumeicon &

#### BSPWM coloring ####
# source the colors.
. "${HOME}/.cache/wal/colors.sh"
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config urgent_border_color  \#dc322f
bspc config presel_feedback_color "$color1"

#### BSPWM configuration ####
bspc config border_width 2
bspc config window_gap   16
bspc config split_ratio         0.50
# bspc config borderless_monocle  true
# bspc config gapless_monocle     true
# bspc config focus_by_distance   true

#### BSPWM workspaces ####
bspc monitor -d 1 2 3 4 5 6 7 8
# bspc rule -a firefox desktop='^1'
