#!/usr/bin/env sh

#### AUTOSTART ####
nitrogen --restore &
alttab -w 1 -d 1 -sc 0 -i 199x64 -t 200x200 -s 3 -bg "#1C1E27" -fg "#cacacc" -frame "#a0c3ff" -font "xft:Roboto:weight=bold:size=11" -theme "WhiteSur-dark" &
blueberry-tray &
clipmenud &
xsetroot -cursor_name left_ptr & # fix cursor size for 4k display
eww daemon &

echo "$(pulsemixer --get-volume | awk '{print $1}')" > /tmp/vol &
exec /etc/eww_vol_icon.sh mute &
for m in $(xrandr --query | grep " connected" | cut -d" " -f1); do
  MONITOR=$m polybar main &
done

# desktop 4
# source: https://www.reddit.com/r/bspwm/comments/ggtwxa/guide_to_creating_startup_layout_using_receptacles/
bspc node @4:/ -i &
bspc node @4:/ -p east -i &
bspc node @4:/1 -p south -i &
bspc node @4:/2 -p south -i &
bspc node @4:/2/2 -p east -i &
bspc rule -a "Slack" -o node=@4:/1/1 &
bspc rule -a "Simplenote" -o node=@4:/1/2 &
bspc rule -a "Evolution" -o node=@4:/2/1 &
bspc rule -a "Gnome-todo" -o node=@4:/2/2/1 &
bspc rule -a "Org.gnome.clocks" -o node=@4:/2/2/2 &
slack &
simplenote &
evolution &
gnome-todo &
gnome-clocks &
# geary &
# gnome-calendar &

#### BSPWM coloring ####
bspc config normal_border_color \#282e3a
bspc config active_border_color \#2C4E9C
bspc config focused_border_color \#a0c3ff
bspc config urgent_border_color  \#dc322f
bspc config presel_feedback_color \#18348D

#### BSPWM configuration ####
bspc config external_rules_command /etc/bspwm_external_rules.sh
bspc config border_width 2
bspc config window_gap   16
bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config swallow_first_click false
bspc config focus_follows_pointer true
bspc config bspc config click_to_focus none
# bspc config focus_by_distance   true

bspc rule -a "mpv" state=floating sticky=on
bspc rule -a ".pick-colour-picker-wrapped" state=floating sticky=on
bspc rule -a "flameshot" state=floating sticky=on
bspc rule -a "Pavucontrol" state=pseudo_tiled
bspc rule -a "Gnome-calculator" state=floating
bspc rule -a "Gnome-font-viewer" state=floating
bspc rule -a "File-roller" state=floating
bspc rule -a "Image Lounge" state=floating
bspc rule -a "Nm-connection-editor" state=floating
bspc rule -a "Cheese" state=pseudo_tiled
bspc rule -a "Blueberry.py" state=floating
bspc rule -a "Gnome-sound-recorder" state=pseudo_tiled
bspc rule -a "Geary" state=pseudo_tiled
bspc rule -a "Gnome-calendar" state=pseudo_tiled
bspc rule -a "Mysql-workbench-bin" state=pseudo_tiled
bspc rule -a "Simplenote" state=pseudo_tiled
bspc rule -a "Org.gnome.clocks" state=pseudo_tiled
bspc rule -a "Gnome-todo" state=pseudo_tiled
bspc rule -a "Gnome-pomodoro" state=pseudo_tiled
bspc rule -a "Gnome-system-monitor" state=floating
bspc rule -a "Eog" state=floating

bspc rule -a "Geary" desktop=^4
bspc rule -a "Gnome-calendar" desktop=^4

#### BSPWM workspaces ####
for m in $(xrandr --query | grep " connected" | cut -d" " -f1); do
  bspc monitor $m -d 1 2 3 4 5 6 7 8
done
