#!/usr/bin/env sh

#### AUTOSTART ####
# wal -R
nitrogen --restore &
alttab -w 1 -d 1 -sc 0 -i 199x64 -t 200x200 -s 3 -bg "#21252b" -fg "#979eae" -frame "#4dd0e1" -font "xft:Work Sans-11" &
blueberry-tray &
volumeicon &
clipmenud &
xsetroot -cursor_name left_ptr & # fix cursor size for 4k display

#### BSPWM coloring ####
# source the colors.
# . "${HOME}/.cache/wal/colors.sh"
bspc config normal_border_color \#282e3a
bspc config active_border_color \#2C4E9C
bspc config focused_border_color \#4dd0e1
bspc config urgent_border_color  \#dc322f
bspc config presel_feedback_color \#18348D

#### BSPWM configuration ####
bspc config border_width 4
bspc config window_gap   16
bspc config split_ratio         0.50
bspc config borderless_monocle  true
# bspc config gapless_monocle     true
# bspc config focus_by_distance   true

bspc rule -a mpv state=floating sticky=on

#### BSPWM workspaces ####
for m in $(xrandr --query | grep " connected" | cut -d" " -f1); do
  bspc monitor $m -d 1 2 3 4 5 6 7 8
done
