# NOTE: Don't use `$HOME` or `~`; Bun uses them literally.
[install]
# where `bun install --global` installs packages
# globalDir = "$HOME/.bun/install/global"

# where globally-installed package bins are linked
# globalBinDir = "$HOME/.bun/bin"

[install.cache]
# the directory to use for the cache
# dir = "$HOME/.bun/install/cache"
