#!/usr/bin/env bash

PROG=$(basename $0)
TEMP=$(getopt --options h --longoptions help toggle togglein -- "$@") || exit 1
eval set -- "$TEMP"

TOGGLE=0
TOGGLEIN=0

for i in "$@"; do
  case "$i" in
  --toggle)
    TOGGLE=1
    break
    ;;
  --togglein)
    TOGGLEIN=1
    break
    ;;
  -h | --help)
    echo "$PROG: --toggle or --togglein" >&2
    exit 0
    ;;
  esac
done

shift

function process_scratchpad() {
  scratchpad=$1
  wk_name=$2
  if [ -n "$scratchpad" ]; then
    ws=$(echo "$scratchpad" | jq -j ".workspace.name")
    address=$(echo "$scratchpad" | jq -j ".address")
    focused=$(echo "$scratchpad" | jq '.focusHistoryID == 0')
    visible=$([ "$ws" == "$current_ws" ] && echo "true" || echo "false")
    if [[ "$visible" == "true" ]]; then
      if [[ "$focused" == "true" ]]; then
        # hide focused scratchpad
        hyprctl dispatch movetoworkspacesilent "special:$wk_name,address:$address" &>/dev/null
        exit 0
      fi
    fi
  fi
}

current_ws="$(hyprctl monitors -j | jq '.[] | select(.focused==true)' | jq -j '.activeWorkspace.name')"

if [ $TOGGLE -eq 1 ]; then
  # if focused window is scratchpad, hide it
  # otherwise show all tmpscratchpads

  # file generated by hyprland-focus-toggle.sh
  state_path="/tmp/hyprland-focus-toggle-state"
  mapfile -t classes <$state_path
  jq_classes=$(printf '%s\n' "${classes[@]}" | jq -R . | jq -s .)

  # loop scratchpads
  scratchpads=$(hyprctl clients -j | jq --argjson classes "$jq_classes" -c '
  .[] | select(
    .workspace.name == "special:scratchpads" or
    (.class | IN($classes[]))
  )
')
  while IFS= read -r scratchpad; do
    process_scratchpad "$scratchpad" "scratchpads"
  done < <(echo "$scratchpads")
  tmpscratchpads=$(hyprctl clients -j | jq --argjson classes "$jq_classes" -c '
  .[] | select(.workspace.name == "special:tmpscratchpads")
')
  while IFS= read -r scratchpad; do
    process_scratchpad "$scratchpad" "tmpscratchpads"
  done < <(echo "$tmpscratchpads")

  # if we didn't hide, then the following line will get executed
  hyprctl dispatch togglespecialworkspace tmpscratchpads
elif [ $TOGGLEIN -eq 1 ]; then
  # move in or move out window from scratchpad

  focused_window="$(hyprctl clients -j | jq '.[] | select(.focusHistoryID == 0 and .workspace.name == "special:tmpscratchpads")')"
  if [ -n "$focused_window" ]; then
    # focused window is in scratchpad

    # move out from scratchpad
    hyprctl dispatch movetoworkspacesilent "$current_ws" &>/dev/null
  else
    # move in to scratchpad
    hyprctl dispatch movetoworkspacesilent "special:tmpscratchpads" &>/dev/null
  fi
fi
