#!/usr/bin/env python3
"""Compose a summary page's Markdown and its library metadata.

usage: compose_summary.py ARTICLE_JSON SUMMARY_MD MODEL OUTPUT_MD

Writes OUTPUT_MD (front matter, header, lead image, summary, original link,
footer) and OUTPUT_MD with a .json suffix (the record `article-library add
--meta` takes). Scraped metadata is escaped; the model's summary is used as is,
since `article-render` disables raw HTML.
"""

import json
import re
import sys
import urllib.parse
from datetime import datetime, timezone
from pathlib import Path


def markdown_text(value):
    value = re.sub(r"[\r\n]+", " ", str(value)).strip()
    return re.sub(r"([\\`*_{}\[\]()<>#+.!|~-])", r"\\\1", value)


def markdown_url(value):
    return str(value).replace("\\", "%5C").replace("<", "%3C").replace(">", "%3E").replace(" ", "%20")


article_path, summary_path, model, output = sys.argv[1:]
article = json.loads(Path(article_path).read_text(encoding="utf-8"))
summary = Path(summary_path).read_text(encoding="utf-8")
canonical = article.get("canonical_url") or ""
source = re.sub(r"^www\.", "", urllib.parse.urlsplit(canonical).hostname or "") or "Web article"
generated_at = datetime.now(timezone.utc).isoformat(timespec="seconds")

metadata = [f"**Source:** {markdown_text(source)}"]
if article.get("author"):
    metadata.append(f"**Author:** {markdown_text(article['author'])}")
if article.get("date"):
    metadata.append(f"**Published:** {markdown_text(article['date'])}")
title = markdown_text(article.get("title") or "Untitled article")
# The linked title becomes the "← All summaries" breadcrumb; pagetitle is the tab title.
# JSON strings are valid YAML scalars, so json.dumps quotes them safely.
front_matter = ["---", f"title: {json.dumps('[All summaries](../index.html)')}", f"pagetitle: {json.dumps(title)}", "---", ""]
parts = front_matter + [f"# {title}", "", "::: metadata", " · ".join(metadata), ":::", ""]
if article.get("image_url"):
    parts += [f"![Lead image](<{markdown_url(article['image_url'])}>){{.lead-image}}", ""]
parts += [
    summary.strip(),
    "",
    f"[Read the original article](<{markdown_url(canonical)}>){{.original}}",
    "",
    "---",
    "",
    "::: footer",
    f"Generated by {markdown_text(model)} at {generated_at} · [All summaries](../index.html)",
    ":::",
    "",
]
Path(output).write_text("\n".join(parts), encoding="utf-8")

record = {
    "title": article.get("title") or "Untitled article",
    "source": source,
    "author": article.get("author") or "",
    "url": canonical,
    "published": article.get("date") or "",
    "image_url": article.get("image_url") or "",
    "model": model,
}
Path(output).with_suffix(".json").write_text(json.dumps(record, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
