{ config, pkgs, lib, ... }:
let
  hostName = "gdesktop";
  # Common values are 96, 120 (25% higher), 144 (50% higher), 168 (75% higher), 192 (100% higher)
  # xlayoutdisplay throws 156
  dpi = 144;
in
{
  imports = [
    # Include the results of the hardware scan.
    /etc/nixos/hardware-configuration.nix

    # Include configuration
    ./config/xorg.nix
  ];

  config = {
    boot = {
      loader = {
        grub.enable = false;
        systemd-boot.enable = true;
        efi.canTouchEfiVariables = true;
      };
      cleanTmpDir = true;
    };

    networking = {
      hostName = hostName;

      # The global useDHCP flag is deprecated, therefore explicitly set to false here.
      # Per-interface useDHCP will be mandatory in the future, so this generated config
      # replicates the default behaviour.
      useDHCP = false;
      interfaces.enp40s0.useDHCP = true;
      interfaces.wlp39s0.useDHCP = true;
    };

    hardware = {
      video.hidpi.enable = true;
    };

    fonts.fontconfig.dpi = dpi;
    services.xserver = {
      dpi = dpi;

      videoDrivers = [
        "nvidia"
      ];

      screenSection = ''
        # Select primary monitor
        Option         "nvidiaXineramaInfoOrder" "DFP-0"
        # Default multiple monitor setup
        Option         "metamodes" "DP-0: 3840x2160_60 +0+0 {ForceCompositionPipeline=Off, ForceFullCompositionPipeline=Off, AllowGSYNCCompatible=On}"
      '';
      deviceSection = ''
        # does it fix screen tearing? NO
        Option         "NoLogo" "1"
        Option         "RenderAccel" "1"
        Option         "TripleBuffer" "true"
        Option         "MigrationHeuristic" "greedy"
        Option         "AccelMethod" "sna"
        Option         "TearFree"    "true"
      '';

      # services.xserver.useGlamor = true;

      # serverLayoutSection = ''
      #   Screen      0  "Screen0" 0 0
      #   Option         "Xinerama" "0"
      # '';
      # extraConfig = ''
      #   Section "Monitor"
      #     # HorizSync source: edid, VertRefresh source: edid
      #     Identifier     "Monitor0"
      #     VendorName     "Unknown"
      #     ModelName      "LG Electronics LG HDR 4K"
      #     HorizSync       135.0 - 135.0
      #     VertRefresh     40.0 - 61.0
      #     Option         "DPMS"
      #   EndSection

      #   Section "Device"
      #     Identifier     "Device0"
      #     Driver         "nvidia"
      #     VendorName     "NVIDIA Corporation"
      #     BoardName      "GeForce GTX 1650 SUPER"

      #     # Generated by nixos
      #     Option         "AccelMethod" "glamor"

      #     # does it fix screen tearing? NO
      #     Option         "NoLogo" "1"
      #     Option         "RenderAccel" "1"
      #     Option         "TripleBuffer" "true"
      #     Option         "MigrationHeuristic" "greedy"
      #     Option         "AccelMethod" "sna"
      #     Option         "TearFree"    "true"
      #   EndSection

      #   Section "Screen"
      #     Identifier     "Screen0"
      #     Device         "Device0"
      #     Monitor        "Monitor0"
      #     DefaultDepth    24
      #     Option         "Stereo" "0"
      #     # Select primary monitor
      #     Option         "nvidiaXineramaInfoOrder" "DFP-0"
      #     # Default multiple monitor setup
      #     Option         "metamodes" "DP-0: 3840x2160_60 +0+0 {ForceCompositionPipeline=Off, ForceFullCompositionPipeline=Off, AllowGSYNCCompatible=On}"
      #     Option         "SLI" "Off"
      #     Option         "MultiGPU" "Off"
      #     Option         "BaseMosaic" "off"
      #     SubSection     "Display"
      #         Depth       24
      #     EndSubSection
      #     # DPI with NVIDIA
      #     # Option         "UseEdidDpi" "FALSE"
      #     # Option         "DPI" "${toString dpi} x ${toString dpi}"
      #   EndSection
      # '';
    };
  };
}
