local-searxng-secret-key: ENC[AES256_GCM,data:KXTmrBxTi4CBYJ92h7UkkPIAPRHi1Y/+Prd1w0mXas3AOl8UBxWjnx7hlGWd3aEA1n2fmNzONAiYeonP1sgb6w==,iv:PPPGHnwUSAf8I3dLLehC6QZms9YEhA1PS6hnfMmcbwk=,tag:ldC4i6VJ36BEAQsgly2DLA==,type:str]
local-omniroute-secret-key: ENC[AES256_GCM,data:aPmw+aE3TCl6PaXtIYraRM/8/pP4cOLc7FH2Y/V0MftmQdE=,iv:UbG4MWhwKu3jNXxBdxGD2Wou6oMrokU9NHEUDHhQN84=,tag:ZtCUiAX4cTohMT91YGSyrw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFVlJKbXpYVWpYTlllN3JF
            RlJrQ0cvaFozNENGcjFoNEVNSGdYRjlta2o4Cms4b0grNDI2S25SU1djakh3Ylgv
            TE5lTTNoUllvVEhDd2JKaVp1VkhUZTgKLS0tIFdTT0VKWEYxTHhEdW1KN0ZUZjFD
            eUlzYnZsZ000ZTlNWnhjd3YzNG8xUXMKipWTsCtfJSsgWsgy3SLVIceitVHfCahx
            odnCpmDB5Y8BfSBhg8a6WutgWQBW5vOkcnteCq+Z1ShjN/k3TK6VqA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age182hl2gfu8zj2dxjdvtfktv9ay57htc20ugjrlmwmv8l806lntdxqgeje73
    lastmodified: "2026-08-16T22:42:46Z"
    mac: ENC[AES256_GCM,data:wvfn2LUKQb6yqOyTce+Nv61e+XkqyIvt6pAQHRzykE9rVDCIouU6ISJkwP/EIBXAhUARgO5DIcSFCAoUA/kRNU9YwZaoSSIEFqJWgfY4HdYKJE9nY8OsGYXXVootKTTNLKl+JtcWV+/0/qIovyg0papMMTRVq5gKT6ltN/zy4sM=,iv:gclrtbIg7xjafKzTEy0PavPSxF+Hk6kACmaBkj4jPfQ=,tag:OA2xyDnAt/It+gHjwfUhMg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
