# Generated by pip2nix 0.8.0.dev1
# See https://github.com/nix-community/pip2nix

{ pkgs, fetchurl, ... }:

self: super: {
  # just for reference
  # "anchor-kr" = super.buildPythonPackage rec {
  #   pname = "anchor-kr";
  #   version = "0.1.3";
  #   src = fetchurl {
  #     url =
  #       "https://files.pythonhosted.org/packages/dd/46/c96feb94c9101ca57b9d612b6510b06da31d31321e5c54fca6cb4a6a0adf/anchor-kr-0.1.3.tar.gz";
  #     sha256 = "1gsbxjahyan617dj91q6bcjg6njk47vkjk6w4l1d56rmznv5bh0g";
  #   };
  #   format = "setuptools";
  #   doCheck = false;
  #   buildInputs = [ ];
  #   checkInputs = [ ];
  #   nativeBuildInputs = [ ];
  #   propagatedBuildInputs = [ ];
  # };
  #
  # "animdl" = super.buildPythonPackage rec {
  #   pname = "animdl";
  #   version = "1.7.22";
  #   src = fetchurl {
  #     url =
  #       "https://files.pythonhosted.org/packages/f3/43/6231c57feb02fe49c2cc2cbd3d40f1a6eeb3c23c93aa4018182364e3a49a/animdl-1.7.22-py3-none-any.whl";
  #     sha256 = "1l373ya31hqci9jalqs6px9j64gn03wyiacsjmxhmn4si6z37fal";
  #   };
  #   format = "wheel";
  #   doCheck = false;
  #   buildInputs = [ ];
  #   checkInputs = [ ];
  #   nativeBuildInputs = [ ];
  #   propagatedBuildInputs = [
  #     self."anchor-kr"
  #     self."anitopy"
  #     pkgs.python311Packages.click
  #     self."comtypes"
  #     pkgs.python311Packages.cssselect
  #     pkgs.python311Packages.httpx
  #     self."lxml"
  #     pkgs.python311Packages.packaging
  #     pkgs.python311Packages.pkginfo
  #     self."pycryptodomex"
  #     pkgs.python311Packages.pyyaml
  #     pkgs.python311Packages.regex
  #     self."rich"
  #     pkgs.python311Packages.tqdm
  #     pkgs.python311Packages.yarl
  #   ];
  # };
}
