model_catalog_json = "~/.codex/model-catalog.local.json"
model_provider = "Model_Studio_Token_Plan_Personal"
model = "qwen3.8-max-preview"

[model_providers.Model_Studio_Token_Plan_Personal]
name = "Model_Studio_Token_Plan_Personal"
base_url = "https://token-plan.ap-southeast-1.maas.aliyuncs.com/compatible-mode/v1"
wire_api = "responses"
