charging:
  90:
    - "notify-send --replace-id=693 --app-name=batty --urgency=normal --app-icon=battery-good-charging --icon=battery-good-charging --hint=int:transient:1 'Battery Nearing Full' 'Your battery is at 90%.'"
  95:
    - "notify-send --replace-id=693 --app-name=batty --urgency=normal --app-icon=battery-full-charged --icon=battery-full-charged --hint=int:transient:1 'Battery Nearing Full' 'Your battery is at 95%.'"
    - "legion-battery-conservation --toggle on"
  100:
    - "notify-send --replace-id=693 --app-name=batty --urgency=normal --app-icon=battery-full-charged --icon=battery-full-charged --hint=int:transient:1 'Battery Charged' 'You can unplug your charger.'"

discharging:
  15:
    - "notify-send --replace-id=693 --app-name=batty --urgency=critical --app-icon=battery-low --icon=battery-low --hint=int:transient:1 'Battery Low' 'Your battery is at 15%.'"
  5:
    - "notify-send --replace-id=693 --app-name=batty --urgency=critical --app-icon=battery-caution --icon=battery-caution --hint=int:transient:1 'Battery Critically Low!' 'Plug in your charger. 5% remaining.'"
