# Shell variables
# Generated by 'wal'
wallpaper='/home/gean/wallpapers/backgrounds/Photo by SpaceX.jpg'

# Special
background='#070E15'
foreground='#d1c8be'
cursor='#d1c8be'

# Colors
color0='#070E15'
color1='#857B2D'
color2='#8A7767'
color3='#958F38'
color4='#9F8A77'
color5='#738484'
color6='#AF9985'
color7='#d1c8be'
color8='#928c85'
color9='#857B2D'
color10='#8A7767'
color11='#958F38'
color12='#9F8A77'
color13='#738484'
color14='#AF9985'
color15='#d1c8be'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
