[general]
targets = ["jira_se"]

[jira_se]
service = "jira"
base_uri = "https://socex-charts.atlassian.net"
username = "@seEmail@"
password = "@oracle:eval:cat /home/gean/.config/secrets/jira/se"
query = "assignee = currentUser() AND statusCategory != Done AND sprint in openSprints() ORDER BY created DESC"
add_tags = ["se"]
project_template = "se"
description_template = "{{ jiraid }} {{ jirasummary }}"

[notifications]
notifications = true
backend = "gobject"
only_on_new_tasks = true

# vim: ft=toml
