#!/usr/bin/env sh

#### AUTOSTART ####
/etc/bspwm_autostart.sh
/etc/restart_goa_daemon.sh

#### Clear rules ####
# bspc rule -r "*"

#### BSPWM coloring ####
bspc config normal_border_color \#282e3a
bspc config active_border_color \#2C4E9C
bspc config focused_border_color \#58a6ff
bspc config urgent_border_color  \#f85149
bspc config presel_feedback_color \#18348D

#### BSPWM configuration ####
bspc config external_rules_command /etc/bspwm_external_rules.sh
bspc config border_width 2
bspc config window_gap   16
bspc config split_ratio         0.5
bspc config borderless_monocle  true
bspc config swallow_first_click false
bspc config focus_follows_pointer true
bspc config bspc config click_to_focus none
bspc config ignore_ewmh_focus true
bspc config single_monocle true
# bspc config focus_by_distance   true

# bspc rule -a *:* state=tiled
bspc rule -a ".caffeine-wrapped" state=floating
bspc rule -a ".pick-colour-picker-wrapped" state=floating sticky=on
bspc rule -a "Blueberry.py" state=floating
bspc rule -a "Cheese" state=pseudo_tiled
bspc rule -a "Com.github.lainsce.notejot" state=floating sticky=on
bspc rule -a "Eog" state=floating
bspc rule -a "Evolution-alarm-notify" state=floating sticky=on
bspc rule -a "File-roller" state=floating
bspc rule -a "Geary" state=pseudo_tiled
bspc rule -a "Gnome-calculator" state=floating
bspc rule -a "Gnome-calendar" state=pseudo_tiled
bspc rule -a "Gnome-font-viewer" state=floating
bspc rule -a "Gnome-sound-recorder" state=pseudo_tiled
bspc rule -a "Gnome-system-monitor" state=floating
bspc rule -a "Image Lounge" state=floating
bspc rule -a "Mysql-workbench-bin" state=pseudo_tiled
bspc rule -a "Nm-connection-editor" state=floating
bspc rule -a "Pavucontrol" state=pseudo_tiled
bspc rule -a "Simplenote" state=pseudo_tiled
bspc rule -a "Sublime_text" state=floating sticky=on
bspc rule -a "flameshot" state=floating sticky=on
bspc rule -a "kmag" state=floating sticky=on
bspc rule -a "mpv" state=floating sticky=on

# bspc rule -a "Geary" desktop=^4
# bspc rule -a "Gnome-calendar" desktop=^4

#### BSPWM workspaces ####
for m in $(xrandr --query | grep " connected" | cut -d" " -f1); do
  bspc monitor $m -d 1 2 3 4 F1 F2 F3 F4
done

# workspace 2
bspc node @2:/ -i
bspc rule -a "kitty:desktop2" -o node=@2:/
kitty --name=desktop2 &

# workspace 1
bspc node @1:/ -i
bspc rule -a "Firefox" -o node=@1:/
sleep 1 &
firefox &

/etc/bspwm_subscribe.sh
